server.name: "kibana"
server.host: "0.0.0.0"
server.basePath: "/kibana"
elasticsearch.hosts: "http://elasticsearch:9200"
apm_oss.enabled: "true"
xpack.apm.enabled: "true"
xpack.apm.ui.enabled: "true"
logging.dest: "stdout"
